"""Hermitian models generated by fixed-partition odd block-TN.

This module implements the six-mode ``U3-A`` model card.  Three two-mode
totally nonnegative (TN) blocks are routed by one *globally synchronized*
``C3`` block permutation,

```
B = P diag(X_0, X_1, X_2).
```

The stronger, direct physical model is the continuous-time Hamiltonian

```
H_CT = -sum_a q_a [Gamma(B_a) + Gamma(B_a)^dagger],  q_a >= 0.
```

All atoms ``B_a`` use the same fixed three-block partition and a grade in
``C3``.  Expanding ``exp(-tau H_CT)`` gives positive Taylor coefficients
times words in ``Gamma(B_a)`` and ``Gamma(B_a^T)``.  Every such one-particle
word remains in the same transpose-closed odd block-TN semigroup, so every
history trace is nonnegative at arbitrary order.  This construction needs
neither a small-coupling bound nor a matrix logarithm.

For comparison, the module retains the discrete transfer version

```
T_beta = I + beta [Gamma(B) + Gamma(B)^dagger],  0 < beta < 1/2,
H_eff = -log(T_beta) / dt.
```

The arbitrary-depth nonnegative-history statement is a theorem, not an
enumeration claim.  ``I``, every ``B_a``, and every ``B_a^T`` belong to the
same fixed block partition with permutation grade in the odd group ``C3``.
In particular, if ``D=diag(X_0,X_1,X_2)`` and ``B=P D``, then

```
B^T = D^T P^(-1)
    = P^(-1) [P D^T P^(-1)].
```

The bracket is again block diagonal, with TN blocks
``(X_1^T, X_2^T, X_0^T)``.  Hence every product of these branches is an odd
block-TN monomial.  Its permutation cycles have odd length, and every cycle
contributes ``det(I + product_of_TN_blocks) >= 0``.  Equivalently,

```
Tr Gamma(B_1 ... B_L) = det(I + B_1 ... B_L) >= 0
```

at every depth.  The finite word enumeration below is only an implementation
regression for this theorem.

The effective-Hamiltonian body audit is deliberately conservative.  It
Möbius-inverts the diagonal Fock matrix elements into density monomials
``prod_(i in S) n_i``.  A nonzero coefficient at order ``|S|`` proves at
least that body order and spatial support; it does not attempt a complete
normal-ordered decomposition of all off-diagonal terms.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
import math
from typing import Sequence

import numpy as np

from oracle.tn_bond_hs import number_conserving_gaussian_fock_matrix


@dataclass(frozen=True)
class OddBlockTNEffectiveModel:
    """Matrices defining the discrete-transfer six-mode model."""

    blocks: tuple[np.ndarray, np.ndarray, np.ndarray]
    permutation: np.ndarray
    branch: np.ndarray
    transpose_branch: np.ndarray
    fock_branch: np.ndarray
    transfer: np.ndarray
    effective_hamiltonian: np.ndarray
    beta: float
    time_step: float


@dataclass(frozen=True)
class ContinuousTimeOddBlockTNModel:
    """A direct six-mode Hamiltonian built from one or more TN atoms."""

    atom_blocks: tuple[
        tuple[np.ndarray, np.ndarray, np.ndarray],
        ...,
    ]
    directions: tuple[int, ...]
    couplings: tuple[float, ...]
    branches: tuple[np.ndarray, ...]
    transpose_branches: tuple[np.ndarray, ...]
    fock_branches: tuple[np.ndarray, ...]
    hamiltonian: np.ndarray


@dataclass(frozen=True)
class BranchHistoryAudit:
    """Finite-depth regression summary for the arbitrary-depth theorem."""

    max_depth: int
    histories: int
    negative_histories: int
    minimum_weight: float
    maximum_imaginary_part: float


@dataclass(frozen=True)
class ContinuousTimeTaylorAudit:
    """Short-word regression for the arbitrary-order Taylor theorem."""

    max_order: int
    histories: int
    negative_histories: int
    minimum_word_weight: float
    minimum_weighted_contribution: float
    maximum_imaginary_part: float
    order_weight_sums: tuple[complex, ...]
    direct_fock_traces: tuple[complex, ...]
    maximum_trace_residual: float


@dataclass(frozen=True)
class EffectiveHamiltonianAudit:
    """Hermiticity, number conservation, and diagonal body-support summary."""

    hermiticity_residual: float
    number_conservation_residual: float
    off_diagonal_norm: float
    maximum_density_body_order: int
    nonzero_density_terms_by_order: tuple[int, ...]
    max_abs_density_coefficient_by_order: tuple[float, ...]
    full_support_density_coefficient: complex
    density_coefficients: np.ndarray


def minimal_tn_blocks() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return the rational two-mode TN contractions from the model card."""

    return (
        np.asarray([[1.0 / 2.0, 1.0 / 4.0], [1.0 / 4.0, 1.0 / 2.0]]),
        np.asarray([[3.0 / 8.0, 1.0 / 8.0], [1.0 / 8.0, 3.0 / 8.0]]),
        np.asarray([[2.0 / 5.0, 1.0 / 10.0], [1.0 / 10.0, 3.0 / 10.0]]),
    )


def _validated_blocks(
    blocks: Sequence[np.ndarray],
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if len(blocks) != 3:
        raise ValueError("fixed C3 routing requires exactly three blocks")
    matrices = tuple(np.asarray(block, dtype=float) for block in blocks)
    block_size = matrices[0].shape[0]
    if block_size < 1 or matrices[0].shape != (block_size, block_size):
        raise ValueError("blocks must be nonempty square matrices")
    if any(matrix.shape != matrices[0].shape for matrix in matrices):
        raise ValueError("all blocks must have the same shape")
    if any(not np.all(np.isfinite(matrix)) for matrix in matrices):
        raise ValueError("blocks must have finite entries")
    return matrices  # type: ignore[return-value]


def c3_block_permutation(block_size: int, *, direction: int = 1) -> np.ndarray:
    """Return the synchronized C3 block permutation in either direction."""

    if block_size < 1:
        raise ValueError("block_size must be positive")
    if direction not in (-1, 0, 1):
        raise ValueError("direction must be -1, 0, or 1")
    identity = np.eye(block_size)
    zero = np.zeros((block_size, block_size))
    forward = np.block(
        [
            [zero, identity, zero],
            [zero, zero, identity],
            [identity, zero, zero],
        ]
    )
    return np.linalg.matrix_power(forward, direction % 3)


def _block_diagonal(blocks: Sequence[np.ndarray]) -> np.ndarray:
    matrices = _validated_blocks(blocks)
    block_size = matrices[0].shape[0]
    result = np.zeros((3 * block_size, 3 * block_size))
    for index, matrix in enumerate(matrices):
        start = index * block_size
        result[start : start + block_size, start : start + block_size] = matrix
    return result


def fixed_c3_block_tn_factor(
    blocks: Sequence[np.ndarray],
    *,
    direction: int = 1,
) -> np.ndarray:
    """Return ``P^direction diag(blocks)`` on one fixed partition."""

    matrices = _validated_blocks(blocks)
    permutation = c3_block_permutation(
        matrices[0].shape[0],
        direction=direction,
    )
    return permutation @ _block_diagonal(matrices)


def transpose_family_blocks(
    blocks: Sequence[np.ndarray],
    *,
    direction: int = 1,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Rewrite ``(P^d diag(blocks))^T`` inside the same C3 family.

    For ``d=1`` and the permutation convention used here,

    ``B^T = P^(-1) diag(X_1^T, X_2^T, X_0^T)``.

    Transposition and block permutation both preserve total
    nonnegativity.
    """

    matrices = _validated_blocks(blocks)
    if direction not in (-1, 0, 1):
        raise ValueError("direction must be -1, 0, or 1")
    return tuple(
        matrices[(index + direction) % 3].T.copy()
        for index in range(3)
    )  # type: ignore[return-value]


def is_tn2_matrix(matrix: np.ndarray, *, tolerance: float = 1e-12) -> bool:
    """Check all minors of one real two-by-two matrix for nonnegativity."""

    candidate = np.asarray(matrix, dtype=float)
    if candidate.shape != (2, 2):
        return False
    return bool(
        np.min(candidate) >= -tolerance
        and np.linalg.det(candidate) >= -tolerance
    )


def is_tn2_contraction(matrix: np.ndarray, *, tolerance: float = 1e-12) -> bool:
    """Check TN and contraction conditions for one real two-by-two block."""

    candidate = np.asarray(matrix, dtype=float)
    return bool(
        is_tn2_matrix(candidate, tolerance=tolerance)
        and np.linalg.norm(candidate, 2) <= 1.0 + tolerance
    )


def build_continuous_time_model(
    atom_blocks: Sequence[Sequence[np.ndarray]],
    *,
    couplings: Sequence[float],
    directions: Sequence[int] | None = None,
) -> ContinuousTimeOddBlockTNModel:
    """Build ``H_CT`` from six-mode atoms in one fixed C3 partition.

    Each atom is ``P^direction diag(X_0,X_1,X_2)``.  The blocks only need to
    be TN; neither their norm nor the nonnegative couplings have an upper
    bound for the Taylor-history theorem.  This executable model is kept at
    two modes per block so the complete 64-dimensional Fock operator remains
    directly auditable.
    """

    families = tuple(_validated_blocks(blocks) for blocks in atom_blocks)
    if not families:
        raise ValueError("at least one atom is required")
    if any(block.shape != (2, 2) for family in families for block in family):
        raise ValueError("the executable model requires two-mode TN blocks")
    if any(
        not is_tn2_matrix(block)
        for family in families
        for block in family
    ):
        raise ValueError("every atom block must be totally nonnegative")

    rates = tuple(float(coupling) for coupling in couplings)
    if len(rates) != len(families):
        raise ValueError("couplings must have one entry per atom")
    if any(not math.isfinite(rate) or rate < 0.0 for rate in rates):
        raise ValueError("couplings must be finite and nonnegative")

    if directions is None:
        grades = (1,) * len(families)
    else:
        grades = tuple(int(direction) for direction in directions)
    if len(grades) != len(families):
        raise ValueError("directions must have one entry per atom")
    if any(direction not in (-1, 0, 1) for direction in grades):
        raise ValueError("directions must be -1, 0, or 1")

    branches = tuple(
        fixed_c3_block_tn_factor(blocks, direction=direction)
        for blocks, direction in zip(families, grades, strict=True)
    )
    transpose_branches = tuple(
        fixed_c3_block_tn_factor(
            transpose_family_blocks(blocks, direction=direction),
            direction=-direction,
        )
        for blocks, direction in zip(families, grades, strict=True)
    )
    for branch, transpose_branch in zip(
        branches,
        transpose_branches,
        strict=True,
    ):
        if not np.allclose(branch.T, transpose_branch, atol=1e-14):
            raise AssertionError("transpose branch rewrite is inconsistent")

    fock_branches = tuple(
        number_conserving_gaussian_fock_matrix(branch)
        for branch in branches
    )
    hamiltonian = np.zeros_like(fock_branches[0], dtype=float)
    for rate, fock_branch in zip(rates, fock_branches, strict=True):
        hamiltonian -= rate * (fock_branch + fock_branch.T)

    return ContinuousTimeOddBlockTNModel(
        atom_blocks=families,
        directions=grades,
        couplings=rates,
        branches=branches,
        transpose_branches=transpose_branches,
        fock_branches=fock_branches,
        hamiltonian=hamiltonian,
    )


def build_minimal_continuous_time_model(
    *,
    coupling: float = 1.0,
) -> ContinuousTimeOddBlockTNModel:
    """Build the direct six-mode ``U3-A`` Hamiltonian with one TN atom."""

    return build_continuous_time_model(
        (minimal_tn_blocks(),),
        couplings=(coupling,),
    )


def hermitian_effective_hamiltonian(
    transfer: np.ndarray,
    *,
    time_step: float = 1.0,
    tolerance: float = 1e-12,
) -> np.ndarray:
    """Return ``-log(transfer)/time_step`` for an SPD Hermitian transfer."""

    matrix = np.asarray(transfer)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("transfer must be square")
    if not math.isfinite(time_step) or time_step <= 0.0:
        raise ValueError("time_step must be finite and positive")
    scale = max(1.0, float(np.linalg.norm(matrix)))
    if np.linalg.norm(matrix - matrix.conj().T) > tolerance * scale:
        raise ValueError("transfer must be Hermitian")
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)
    if float(np.min(eigenvalues)) <= tolerance:
        raise ValueError("transfer must be strictly positive definite")
    logarithm = (eigenvectors * np.log(eigenvalues)) @ eigenvectors.conj().T
    return -logarithm / time_step


def build_minimal_model(
    *,
    beta: float = 1.0 / 4.0,
    time_step: float = 1.0,
) -> OddBlockTNEffectiveModel:
    """Build the directly encodable six-mode ``U3-A`` instance."""

    if not math.isfinite(beta) or not 0.0 < beta < 0.5:
        raise ValueError("beta must satisfy 0 < beta < 1/2")
    blocks = minimal_tn_blocks()
    if not all(is_tn2_contraction(block) for block in blocks):
        raise AssertionError("minimal blocks must be TN contractions")

    permutation = c3_block_permutation(2)
    branch = fixed_c3_block_tn_factor(blocks)
    rewritten_transpose = fixed_c3_block_tn_factor(
        transpose_family_blocks(blocks),
        direction=-1,
    )
    if not np.allclose(branch.T, rewritten_transpose, atol=1e-14):
        raise AssertionError("transpose branch rewrite is inconsistent")

    fock_branch = number_conserving_gaussian_fock_matrix(branch)
    transfer = np.eye(fock_branch.shape[0]) + beta * (
        fock_branch + fock_branch.T
    )
    effective = hermitian_effective_hamiltonian(
        transfer,
        time_step=time_step,
    )
    return OddBlockTNEffectiveModel(
        blocks=blocks,
        permutation=permutation,
        branch=branch,
        transpose_branch=rewritten_transpose,
        fock_branch=fock_branch,
        transfer=transfer,
        effective_hamiltonian=effective,
        beta=float(beta),
        time_step=float(time_step),
    )


def branch_history_audit(
    model: OddBlockTNEffectiveModel,
    *,
    max_depth: int,
) -> BranchHistoryAudit:
    """Enumerate short branch words as a regression, not as the proof."""

    if max_depth < 1:
        raise ValueError("max_depth must be positive")
    dimension = model.branch.shape[0]
    identity = np.eye(dimension)
    branches = (identity, model.branch, model.transpose_branch)
    histories = 0
    negative = 0
    minimum = math.inf
    maximum_imaginary = 0.0

    for depth in range(1, max_depth + 1):
        for word in product(range(len(branches)), repeat=depth):
            propagation = identity.copy()
            for branch_index in word:
                propagation = propagation @ branches[branch_index]
            weight = complex(np.linalg.det(identity + propagation))
            histories += 1
            minimum = min(minimum, float(weight.real))
            maximum_imaginary = max(maximum_imaginary, abs(weight.imag))
            if weight.real < -1e-12 or abs(weight.imag) > 1e-10:
                negative += 1

    return BranchHistoryAudit(
        max_depth=max_depth,
        histories=histories,
        negative_histories=negative,
        minimum_weight=minimum,
        maximum_imaginary_part=maximum_imaginary,
    )


def continuous_time_taylor_audit(
    model: ContinuousTimeOddBlockTNModel,
    *,
    max_order: int,
) -> ContinuousTimeTaylorAudit:
    """Regress Taylor words against direct powers of ``-H_CT``.

    The determinant check samples the theorem only at short order.  The
    separate equality

    ``sum_words product(q) det(I + product(B)) = Tr[(-H_CT)^order]``

    verifies that the enumerated histories are exactly the Taylor expansion
    of the physical Hamiltonian, rather than an unrelated positive ensemble.
    """

    if max_order < 0:
        raise ValueError("max_order must be nonnegative")

    one_particle_branches: list[np.ndarray] = []
    branch_couplings: list[float] = []
    for rate, branch, transpose_branch in zip(
        model.couplings,
        model.branches,
        model.transpose_branches,
        strict=True,
    ):
        one_particle_branches.extend((branch, transpose_branch))
        branch_couplings.extend((rate, rate))

    mode_dimension = model.branches[0].shape[0]
    fock_dimension = model.hamiltonian.shape[0]
    identity = np.eye(mode_dimension)
    histories = 0
    negative = 0
    minimum_word = math.inf
    minimum_weighted = math.inf
    maximum_imaginary = 0.0
    order_sums: list[complex] = []
    direct_traces: list[complex] = []
    maximum_residual = 0.0

    for order in range(max_order + 1):
        words = ((),) if order == 0 else product(
            range(len(one_particle_branches)),
            repeat=order,
        )
        order_sum = 0.0j
        for word in words:
            propagation = identity.copy()
            coefficient = 1.0
            for branch_index in word:
                propagation = (
                    propagation @ one_particle_branches[branch_index]
                )
                coefficient *= branch_couplings[branch_index]

            word_weight = complex(np.linalg.det(identity + propagation))
            weighted_contribution = coefficient * word_weight
            histories += 1
            minimum_word = min(minimum_word, float(word_weight.real))
            minimum_weighted = min(
                minimum_weighted,
                float(weighted_contribution.real),
            )
            maximum_imaginary = max(
                maximum_imaginary,
                abs(word_weight.imag),
                abs(weighted_contribution.imag),
            )
            if word_weight.real < -1e-12 or abs(word_weight.imag) > 1e-10:
                negative += 1
            order_sum += weighted_contribution

        direct_trace = complex(
            np.trace(
                np.linalg.matrix_power(-model.hamiltonian, order)
                if order
                else np.eye(fock_dimension)
            )
        )
        residual = abs(order_sum - direct_trace)
        maximum_residual = max(maximum_residual, residual)
        order_sums.append(order_sum)
        direct_traces.append(direct_trace)

    return ContinuousTimeTaylorAudit(
        max_order=max_order,
        histories=histories,
        negative_histories=negative,
        minimum_word_weight=minimum_word,
        minimum_weighted_contribution=minimum_weighted,
        maximum_imaginary_part=maximum_imaginary,
        order_weight_sums=tuple(order_sums),
        direct_fock_traces=tuple(direct_traces),
        maximum_trace_residual=maximum_residual,
    )


def diagonal_density_coefficients(operator: np.ndarray) -> np.ndarray:
    """Möbius-invert Fock diagonals into products of occupation numbers."""

    matrix = np.asarray(operator)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("operator must be square")
    dimension = matrix.shape[0]
    modes = int(round(math.log2(dimension)))
    if 1 << modes != dimension:
        raise ValueError("operator dimension must be a power of two")

    diagonal = np.diag(matrix)
    coefficients = np.zeros(
        dimension,
        dtype=np.result_type(matrix.dtype, np.complex128),
    )
    for mask in range(dimension):
        subset = mask
        value = 0.0j
        while True:
            parity = (mask.bit_count() - subset.bit_count()) & 1
            value += (-1 if parity else 1) * diagonal[subset]
            if subset == 0:
                break
            subset = (subset - 1) & mask
        coefficients[mask] = value
    return coefficients


def effective_hamiltonian_audit(
    hamiltonian: np.ndarray,
    *,
    coefficient_tolerance: float = 1e-12,
) -> EffectiveHamiltonianAudit:
    """Audit a number-conserving Fock Hamiltonian and its density support."""

    matrix = np.asarray(hamiltonian)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        raise ValueError("hamiltonian must be square")
    dimension = matrix.shape[0]
    modes = int(round(math.log2(dimension)))
    if 1 << modes != dimension:
        raise ValueError("hamiltonian dimension must be a power of two")

    number_diagonal = np.asarray(
        [mask.bit_count() for mask in range(dimension)],
        dtype=float,
    )
    number_operator = np.diag(number_diagonal)
    coefficients = diagonal_density_coefficients(matrix)

    counts: list[int] = []
    maxima: list[float] = []
    maximum_order = 0
    for order in range(modes + 1):
        order_coefficients = np.asarray(
            [
                coefficients[mask]
                for mask in range(dimension)
                if mask.bit_count() == order
            ]
        )
        magnitudes = np.abs(order_coefficients)
        count = int(np.count_nonzero(magnitudes > coefficient_tolerance))
        counts.append(count)
        maxima.append(float(np.max(magnitudes)))
        if count:
            maximum_order = order

    off_diagonal = matrix - np.diag(np.diag(matrix))
    scale = max(1.0, float(np.linalg.norm(matrix)))
    return EffectiveHamiltonianAudit(
        hermiticity_residual=float(
            np.linalg.norm(matrix - matrix.conj().T) / scale
        ),
        number_conservation_residual=float(
            np.linalg.norm(matrix @ number_operator - number_operator @ matrix)
            / scale
        ),
        off_diagonal_norm=float(np.linalg.norm(off_diagonal)),
        maximum_density_body_order=maximum_order,
        nonzero_density_terms_by_order=tuple(counts),
        max_abs_density_coefficient_by_order=tuple(maxima),
        full_support_density_coefficient=complex(coefficients[-1]),
        density_coefficients=coefficients,
    )
